name: wp_theme

on:
  pull_request:
    types: [opened, reopened]

jobs:
  check_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - name: install dependencies
        run: yarn
      - name: test project
        run: yarn test
      - name: build project
        run: yarn build
